In [453]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [454]:
dfTrain = pd.read_csv("train.csv",header=0)
dfTest = pd.read_csv("test.csv",header=0)
yTest = pd.read_csv("sample_submission.csv",header=0)

In [455]:
dfTrain.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [456]:
dfTrain = dfTrain.set_index("Id")
dfTest = dfTest.set_index("Id")
yTest = yTest.set_index("Id")
dfTrain.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [457]:
for col in dfTrain.columns[dfTrain.isna().any()].tolist():
    if(dfTrain[col].dtype == "object"):
        dfTrain[col].fillna("unknown", inplace=True)
    if((dfTrain[col].dtype == "float64") or (dfTrain[col].dtype == "int64")):
        dfTrain[col].fillna(dfTrain[col].mean(), inplace=True)
for col in dfTest.columns[dfTest.isna().any()].tolist():
    if(dfTest[col].dtype == "object"):
        dfTest[col].fillna("unknown", inplace=True)
    if((dfTest[col].dtype == "float64") or (dfTest[col].dtype == "int64")):
        dfTest[col].fillna(dfTest[col].mean(), inplace=True)

In [458]:
dfTrain.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,unknown,Reg,Lvl,AllPub,Inside,...,0,unknown,unknown,unknown,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,unknown,Reg,Lvl,AllPub,FR2,...,0,unknown,unknown,unknown,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,unknown,IR1,Lvl,AllPub,Inside,...,0,unknown,unknown,unknown,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,unknown,IR1,Lvl,AllPub,Corner,...,0,unknown,unknown,unknown,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,unknown,IR1,Lvl,AllPub,FR2,...,0,unknown,unknown,unknown,0,12,2008,WD,Normal,250000

In [459]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in dfTest:
    if(dfTest[col].dtype == "object"):
        data = dfTrain[col].append(dfTest[col])
        encoder.fit(data.values)
        dfTrain[col] = encoder.transform(dfTrain[col])
        dfTest[col] = encoder.transform(dfTest[col])

In [460]:
dfTrain['MSZoning'].unique()

array([3, 4, 0, 1, 2])

In [464]:
df_corr = (pd.DataFrame(dfTrain.corr()['SalePrice']))
df_corr = df_corr.sort_values('SalePrice',ascending=False)
df_corr

               SalePrice
SalePrice       1.000000
OverallQual     0.790982
GrLivArea       0.708624
GarageCars      0.640409
GarageArea      0.623431
TotalBsmtSF     0.613581
1stFlrSF        0.605852
FullBath        0.560664
TotRmsAbvGrd    0.533723
YearBuilt       0.522897
YearRemodAdd    0.507101
MasVnrArea      0.475241
GarageYrBlt     0.470177
Fireplaces      0.466929
BsmtFinSF1      0.386420
Foundation      0.382479
LotFrontage     0.334901
WoodDeckSF      0.324413
2ndFlrSF        0.319334
OpenPorchSF     0.315856
HalfBath        0.284108
LotArea         0.263843
CentralAir      0.251328
Electrical      0.234716
PavedDrive      0.231357
BsmtFullBath    0.227122
RoofStyle       0.222405
BsmtUnfSF       0.214479
SaleCondition   0.213092
Neighborhood    0.210851
...                  ...
BsmtCond        0.015058
BsmtFinType2    0.008041
Condition2      0.007513
GarageQual      0.006861
BsmtFinSF2     -0.011378
Utilities      -0.014314
BsmtHalfBath   -0.016844
MiscVal        -0.021190
LowQualFinSF   -0.025606
YrSold         -0.028923
SaleType       -0.054911
LotConfig      -0.067396
OverallCond    -0.077856
MSSubClass     -0.084284
BldgType       -0.085591
Heating        -0.098812
BsmtFinType1   -0.103114
PoolQC         -0.126070
EnclosedPorch  -0.128578
KitchenAbvGr   -0.135907
MSZoning       -0.166872
LotShape       -0.255580
BsmtExposure   -0.309043
HeatingQC      -0.400178
GarageType     -0.415283
FireplaceQu    -0.459605
GarageFinish   -0.549247
KitchenQual    -0.589189
BsmtQual       -0.620886
ExterQual      -0.636884

[80 rows x 1 columns]

In [479]:
df_corr_list = list(df_corr.index.values)
temp = df_corr_list[1:11]
temp1 = df_corr_list[-4:-1]
temp = temp + temp1
temp.append(df_corr_list[-1])
temp

['OverallQual',
 'GrLivArea',
 'GarageCars',
 'GarageArea',
 'TotalBsmtSF',
 '1stFlrSF',
 'FullBath',
 'TotRmsAbvGrd',
 'YearBuilt',
 'YearRemodAdd',
 'GarageFinish',
 'KitchenQual',
 'BsmtQual',
 'ExterQual']

In [481]:
dfTrain = dfTrain[temp+['SalePrice']]
dfTest = dfTest[temp]

In [482]:
df_corr = (pd.DataFrame(dfTrain.corr()['SalePrice']))
df_corr.sort_values('SalePrice',ascending=False)

              SalePrice
SalePrice      1.000000
OverallQual    0.790982
GrLivArea      0.708624
GarageCars     0.640409
GarageArea     0.623431
TotalBsmtSF    0.613581
1stFlrSF       0.605852
FullBath       0.560664
TotRmsAbvGrd   0.533723
YearBuilt      0.522897
YearRemodAdd   0.507101
GarageFinish  -0.549247
KitchenQual   -0.589189
BsmtQual      -0.620886
ExterQual     -0.636884

In [483]:
dfTest.head()

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd,GarageFinish,KitchenQual,BsmtQual,ExterQual
Id,,,,,,,,,,,,,,
1461,5,896,1.0,730.0,882.0,896,1,5,1961,1961,2,3,3,3
1462,6,1329,1.0,312.0,1329.0,1329,1,6,1958,1958,2,2,3,3
1463,5,1629,2.0,482.0,928.0,928,2,6,1997,1998,0,3,2,3
1464,6,1604,2.0,470.0,926.0,926,2,7,1998,1998,0,2,3,3
1465,8,1280,2.0,506.0,1280.0,1280,2,5,1992,1992,1,2,2,2

In [484]:
XTrain = dfTrain.drop(['SalePrice'],1)
yTrain = np.array(dfTrain['SalePrice'])
XTest = dfTest
yTest = np.array(yTest['SalePrice'])

In [485]:
XTrain.head()

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd,GarageFinish,KitchenQual,BsmtQual,ExterQual
Id,,,,,,,,,,,,,,
1,7,1710,2,548,856,856,2,8,2003,2003,1,2,2,2
2,6,1262,2,460,1262,1262,2,6,1976,1976,1,3,2,3
3,7,1786,2,608,920,920,2,6,2001,2002,1,2,2,2
4,7,1717,3,642,756,961,1,7,1915,1970,2,2,3,3
5,8,2198,3,836,1145,1145,2,9,2000,2000,1,2,2,2

In [486]:
from sklearn.preprocessing import scale
XTrainScaled = scale(XTrain)
XTestScaled = scale(XTest)
# XTrainScaled = np.array(XTrain)
# XTestScaled = np.array(XTest)

In [507]:
from sklearn import svm
from sklearn.linear_model import LinearRegression
clf = svm.SVR(C=10000,epsilon=5,gamma=0.0005)
clf.fit(XTrainScaled,yTrain)

SVR(C=10000, cache_size=200, coef0=0.0, degree=3, epsilon=5, gamma=0.0005,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [509]:
from sklearn.metrics import accuracy_score
yPrdeict = clf.predict(XTestScaled)
r2 = clf.score(XTest,yPrdeict)
r2_train = clf.score(XTrain,yTrain)

# for i in range(50):
#     print("ytest:{}  ypredict:{}".format(yTest[i],yPrdeict[i]))
r2_train

-0.0004998631331167847